version: 2

models:
  - name: q1
    description: "Pricing Summary Report (Отчет об итогах ценообразования)"
    meta:
      label: "q1: Итоги ценообразования"
    columns:
      - name: l_returnflag
        description: "Флаг возврата позиции"
        meta:
          dimension:
            type: string
            label: "Флаг возврата"
      - name: l_linestatus
        description: "Статус доставки позиции"
        meta:
          dimension:
            type: string
            label: "Статус доставки"
      - name: sum_qty
        description: "Общее количество заказанных деталей"
        meta:
          metrics:
            total_quantity:
              type: sum
              label: "Суммарное количество деталей"
      - name: sum_base_price
        description: "Суммарная базовая стоимость"
        meta:
          metrics:
            total_base_price:
              type: sum
              label: "Суммарная базовая цена"
      - name: sum_disc_price
        description: "Суммарная стоимость со скидкой"
        meta:
          metrics:
            total_discounted_price:
              type: sum
              label: "Суммарная цена со скидкой"
      - name: sum_charge
        description: "Суммарная стоимость со скидкой и налогом"
        meta:
          metrics:
            total_charge:
              type: sum
              label: "Итоговая сумма с налогом"
      - name: avg_qty
        description: "Среднее количество деталей"
        meta:
          metrics:
            average_quantity:
              type: average
              label: "Среднее количество"
      - name: avg_price
        description: "Средняя цена позиции"
        meta:
          metrics:
            average_price:
              type: average
              label: "Средняя цена"
      - name: avg_disc
        description: "Средняя скидка"
        meta:
          metrics:
            average_discount:
              type: average
              label: "Средний размер скидки"
      - name: count_order
        description: "Общее количество позиций"
        meta:
          metrics:
            total_order_lines:
              type: sum
              label: "Количество отгруженных позиций"

  - name: q3
    description: "Shipping Priority (Определение ТОП-10 заказов с наивысшим доходом)"
    meta:
      label: "q3: Приоритеты доставки"
    columns:
      - name: l_orderkey
        description: "Идентификатор заказа"
        meta:
          dimension:
            type: number
            label: "ID Заказа"
      - name: revenue
        description: "Доход от заказа"
        meta:
          metrics:
            total_revenue:
              type: sum
              label: "Суммарный доход"
      - name: o_orderdate
        description: "Дата заказа"
        meta:
          dimension:
            type: date
            label: "Дата заказа"
      - name: o_shippriority
        description: "Приоритет отгрузки"
        meta:
          dimension:
            type: number
            label: "Приоритет отгрузки"

  - name: q5
    description: "Local Supplier Volume (Выручка местных поставщиков по странам)"
    meta:
      label: "q5: Выручка местных поставщиков"
    columns:
      - name: n_name
        description: "Страна"
        meta:
          dimension:
            type: string
            label: "Страна"
      - name: revenue
        description: "Выручка со скидкой"
        meta:
          metrics:
            total_supplier_revenue:
              type: sum
              label: "Суммарная выручка поставщиков"

  - name: q7
    description: "Volume Shipping (Объем перевозок между странами)"
    meta:
      label: "q7: Объем перевозок между странами"
    columns:
      - name: supp_nation
        description: "Страна отправителя"
        meta:
          dimension:
            type: string
            label: "Страна отправителя"
      - name: cust_nation
        description: "Страна получателя"
        meta:
          dimension:
            type: string
            label: "Страна получателя"
      - name: l_year
        description: "Год отгрузки"
        meta:
          dimension:
            type: number
            label: "Год отгрузки"
      - name: revenue
        description: "Выручка"
        meta:
          metrics:
            total_shipping_revenue:
              type: sum
              label: "Суммарная выручка от перевозок"

  - name: q8
    description: "National Market Share (Доля рынка конкретной страны)"
    meta:
      label: "q8: Доля национального рынка"
    columns:
      - name: o_year
        description: "Год заказа"
        meta:
          dimension:
            type: number
            label: "Год заказа"
      - name: mkt_share
        description: "Доля рынка"
        meta:
          metrics:
            avg_market_share:
              type: average
              label: "Средняя доля рынка"

  - name: q9
    description: "Product Type Profit Measure (Прибыль по типу деталей и странам)"
    meta:
      label: "q9: Прибыль по типу деталей"
    columns:
      - name: nation
        description: "Страна поставщика"
        meta:
          dimension:
            type: string
            label: "Страна поставщика"
      - name: o_year
        description: "Год заказа"
        meta:
          dimension:
            type: number
            label: "Год заказа"
      - name: sum_profit
        description: "Годовая чистая прибыль"
        meta:
          metrics:
            total_profit:
              type: sum
              label: "Общая чистая прибыль"
            average_profit:
              type: average
              label: "Средняя чистая прибыль"

  - name: q10
    description: "Returned Item Reporting (Отчет о возвратах товаров)"
    meta:
      label: "q10: Отчет о возвратах товаров"
    columns:
      - name: c_custkey
        description: "ID Клиента"
        meta:
          dimension:
            type: number
            label: "ID Клиента"
      - name: c_name
        description: "Имя клиента"
        meta:
          dimension:
            type: string
            label: "Имя клиента"
      - name: revenue
        description: "Потери от возвратов"
        meta:
          metrics:
            total_returned_loss:
              type: sum
              label: "Общие потери от возвратов"
      - name: c_acctbal
        description: "Баланс счета клиента"
        meta:
          dimension:
            type: number
            label: "Баланс счета"
      - name: n_name
        description: "Страна клиента"
        meta:
          dimension:
            type: string
            label: "Страна клиента"
